[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = [
  'npm ci --prefer-offline --no-audit --silent',
  'cd server && npm ci --prefer-offline --no-audit --silent',
  'cd client && npm ci --prefer-offline --no-audit --silent'
]

[phases.build]
cmds = [
  'cd server && npm run build',
  'cd client && npm run build',
  'mkdir -p server/data logs'
]

[start]
cmd = 'node railway-start.js'

[variables]
NODE_ENV = 'production'
HOST = '0.0.0.0' 