[phases.setup]
nixPkgs = ["nodejs_20", "python3"]

[phases.install]
cmds = [
  "npm ci --prefer-offline --no-audit"
]

[phases.build]
cmds = [
  "npm run build:server",
  "npm run build:client"
]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false" 