[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"
CORS_ORIGIN = "${{RAILWAY_PUBLIC_DOMAIN}}"
PORT = "${{PORT}}" 