[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
healthcheckInterval = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
startCommand = "npm start"

[env]
NODE_ENV = "production"
CORS_ORIGIN = "${{RAILWAY_PUBLIC_DOMAIN}}" 