import { Asset, Signal } from '../models';
import logger from '../utils/logger';
import notificationService from './notificationService';
import { calculateStrength } from '../utils/signalUtils';

/**
 * Signal Generator Service
 * Note: This no longer generates simulated signals
 * Real signals now come from:
 * 1. Price monitoring service (priceService)
 * 2. Future: Social media sentiment analysis
 * 3. Future: News sentiment analysis  
 * 4. Future: Technical indicator analysis
 */

class RealSignalGenerator {
  private intervalId: NodeJS.Timeout | null = null;

  /**
   * Start signal generator
   * Note: Now no longer generates simulated signals
   */
  start(): void {
    logger.info('⚠️  Simulated signal generator is disabled');
    logger.info('📊 Signals now come from real data sources:');
    logger.info('   - Price monitoring service (real-time price changes)');
    logger.info('   - To be added: Social media sentiment analysis');
    logger.info('   - To be added: News sentiment analysis');
    logger.info('   - To be added: Technical indicator analysis');
    
    // No longer start timer to generate simulated signals
    // Real signals are actively generated by various data source services
  }

  /**
   * Stop signal generator
   */
  stop(): void {
    if (this.intervalId) {
      clearInterval(this.intervalId);
      this.intervalId = null;
      logger.info('Signal generator stopped');
    }
  }

  /**
   * Manually add sentiment signal (for use when API integration)
   */
  async createSentimentSignal(
    assetSymbol: string, 
    sentimentScore: number, 
    sources: Array<{platform: 'twitter' | 'reddit', count: number}>
  ): Promise<void> {
    try {
      const asset = await Asset.findOne({ where: { symbol: assetSymbol } });
      if (!asset) {
        logger.error(`Asset does not exist: ${assetSymbol}`);
        return;
      }

      // Generate description based on sentiment score
      let description = '';
      if (sentimentScore > 0.6) {
        description = `${asset.name} sentiment on social media is significantly positive, investor mood is optimistic`;
      } else if (sentimentScore < -0.6) {
        description = `${asset.name} sentiment on social media is significantly negative, investor mood is cautious`;
      } else {
        description = `${asset.name} sentiment on social media remains neutral`;
      }

      // Calculate signal strength
      const strength = calculateStrength(Math.abs(sentimentScore * 100), 'sentiment');

      const signal = await Signal.create({
        assetId: asset.id,
        assetSymbol: asset.symbol,
        assetName: asset.name,
        assetLogo: asset.logo,
        type: 'sentiment',
        strength,
        description,
        sources,
        timestamp: new Date()
      });

      logger.info(`Generated sentiment signal: ${assetSymbol} (score: ${sentimentScore}, strength: ${strength})`);
      await notificationService.processSignal(signal);

    } catch (error) {
      logger.error('Failed to create sentiment signal:', error);
    }
  }

  /**
   * Manually add narrative signal (for use when API integration)
   */
  async createNarrativeSignal(
    assetSymbol: string, 
    narrativeType: string, 
    description: string, 
    sources: Array<{platform: 'twitter' | 'reddit', count: number}>
  ): Promise<void> {
    try {
      const asset = await Asset.findOne({ where: { symbol: assetSymbol } });
      if (!asset) {
        logger.error(`Asset does not exist: ${assetSymbol}`);
        return;
      }

      // Calculate strength based on narrative type
      const narrativeStrengthMap: Record<string, number> = {
        'upgrade': 80,
        'partnership': 70,
        'adoption': 75,
        'regulation': 60,
        'technical': 65
      };

      const strength = narrativeStrengthMap[narrativeType] || 50;

      const signal = await Signal.create({
        assetId: asset.id,
        assetSymbol: asset.symbol,
        assetName: asset.name,
        assetLogo: asset.logo,
        type: 'narrative',
        strength,
        description,
        sources,
        timestamp: new Date()
      });

      logger.info(`Generated narrative signal: ${assetSymbol} (type: ${narrativeType}, strength: ${strength})`);
      await notificationService.processSignal(signal);

    } catch (error) {
      logger.error('Failed to create narrative signal:', error);
    }
  }

  /**
   * Get pending data source status
   */
  getDataSourceStatus(): Record<string, boolean> {
    return {
      'priceMonitoring': true,    // Implemented
      'twitterSentiment': false,  // To be implemented
      'redditSentiment': false,   // To be implemented
      'newsAnalysis': false,      // To be implemented
      'technicalAnalysis': false // To be implemented
    };
  }
}

// Export singleton
const realSignalGenerator = new RealSignalGenerator();

/**
 * Initialize signal generation services
 */
export const initializeSignalGenerator = () => {
  realSignalGenerator.start();
};

export default realSignalGenerator; 